ALTER TABLE pages ADD COLUMN seo_title VARCHAR(70) NOT NULL DEFAULT '';
ALTER TABLE pages ADD COLUMN seo_description VARCHAR(160) NOT NULL DEFAULT '';
ALTER TABLE pages ADD COLUMN noindex BOOLEAN NOT NULL DEFAULT false;
