// Galeri ikon siap-pakai -- permintaan langsung pengguna, 13 Agustus 2026:
// "saya mau tambahkan untuk memilih icon untuk blok yang sudah disediakan
// dari web ini jadi sediakan banyak icon yang bisa digunakan dan dipilih
// user supaya user tidak perlu mendowload icon sendiri dan mengupload ke
// web ini". SATU-SATUNYA tempat proyek ini menambah dependency ikon
// eksternal (lucide-react) -- beda dari components/icons.tsx (ikon garis
// hand-drawn KHUSUS untuk chrome UI dashboard sendiri, cuma ~44 ikon,
// tidak dirancang jadi galeri pilihan pengguna) -- kebutuhan di sini
// genuinely perlu RATUSAN ikon lintas kategori supaya "sediakan banyak
// icon" benar-benar terpenuhi, mustahil digambar tangan satu-satu seperti
// set ikon UI yang sudah ada.
//
// `key` -- string stabil disimpan di links.icon_key (migrasi 000066),
// SENGAJA memakai nama asli lucide dalam kebab-case (bukan angka index
// array) supaya urutan di IconPickerModal boleh berubah kapan pun tanpa
// merusak ikon yang sudah dipilih kreator sebelumnya. `label` teks
// Indonesia untuk pencarian & tooltip.
//
// Kategori "Media Sosial" (20 Agustus 2026, permintaan langsung pengguna:
// "tambahkan juga di bagian icon supaya bisa dipilih" -- susulan dari
// penggantian ikon sosmed di components/icons.tsx) MENGECUALIKAN aturan
// "satu-satunya dependency eksternal" di atas -- ikon brand (Instagram,
// TikTok, dst, prefix key "brand-") diimpor LANGSUNG dari icons.tsx
// (Simple Icons, sudah akurat & dikenal), bukan dicari padanan lucide-nya
// (lucide-react tidak punya logo brand sama sekali). `Icon` karena itu
// diketik generik (bukan LucideIcon murni) supaya menerima keduanya --
// IconPickerModal cuma pernah merender `<icon.Icon className="..." />`,
// jadi cukup kompatibel selama komponennya menerima prop `className`.
import type { ComponentType } from "react";
import {
  IconAppleMusic,
  IconApplePodcasts,
  IconDiscord,
  IconFacebook,
  IconGoogleMaps,
  IconInstagram,
  IconLinkedin,
  IconShopee,
  IconSpotify,
  IconTelegram,
  IconTiktok,
  IconTwitch,
  IconWhatsapp,
  IconX,
  IconYoutube,
} from "@/components/icons";
import type { LucideIcon } from "lucide-react";
import {
  MessageCircle,
  MessageSquare,
  Send,
  Mail,
  Phone,
  PhoneCall,
  Video,
  Mic,
  Mic2,
  Users,
  User,
  UserPlus,
  Heart,
  HeartHandshake,
  ThumbsUp,
  Share2,
  AtSign,
  Hash,
  Rss,
  Bell,
  ShoppingBag,
  ShoppingCart,
  Store,
  Tag,
  Tags,
  CreditCard,
  Wallet,
  DollarSign,
  Receipt,
  Package,
  Gift,
  Percent,
  Briefcase,
  Building,
  Building2,
  TrendingUp,
  BarChart,
  PieChart,
  Target,
  Award,
  Handshake,
  Coffee,
  Pizza,
  IceCream,
  Cake,
  Utensils,
  UtensilsCrossed,
  Wine,
  Beer,
  Soup,
  Apple,
  Cherry,
  Croissant,
  Plane,
  Car,
  Bike,
  Train,
  Ship,
  MapPin,
  Map,
  Compass,
  Globe,
  Luggage,
  Palmtree,
  Mountain,
  Tent,
  Backpack,
  Music,
  Music2,
  Music3,
  Music4,
  Headphones,
  Radio,
  Disc,
  Disc3,
  Film,
  Clapperboard,
  Tv,
  Gamepad,
  Gamepad2,
  PartyPopper,
  Ticket,
  Dumbbell,
  Trophy,
  Medal,
  Volleyball,
  Activity,
  Flame,
  Zap,
  Timer,
  Laptop,
  Smartphone,
  Monitor,
  Camera,
  Cpu,
  Wifi,
  Bluetooth,
  Code,
  Terminal,
  Database,
  Cloud,
  Rocket,
  Battery,
  Printer,
  Keyboard,
  Mouse,
  HardDrive,
  Sun,
  Moon,
  Star,
  CloudRain,
  Snowflake,
  Wind,
  Umbrella,
  Leaf,
  Flower,
  Flower2,
  Trees,
  TreePine,
  Droplet,
  Waves,
  Sunrise,
  Sunset,
  Palette,
  Brush,
  PenTool,
  Pencil,
  Scissors,
  Image,
  Images,
  Sparkles,
  Sparkle,
  Wand2,
  Book,
  BookOpen,
  Bookmark,
  Feather,
  Home,
  Sofa,
  Bed,
  Lamp,
  Key,
  ShowerHead,
  Bath,
  Shirt,
  Watch,
  Glasses,
  Crown,
  Gem,
  GraduationCap,
  School,
  Calculator,
  Ruler,
  Library,
  HeartPulse,
  Stethoscope,
  Pill,
  Syringe,
  Brain,
  Eye,
  Smile,
  Diamond,
  Flag,
  Anchor,
  Puzzle,
  Infinity,
  PawPrint,
  Fish,
  Bird,
  Bug,
  Rabbit,
  Turtle,
  Sprout,
  Salad,
  Popcorn,
  Martini,
  CupSoda,
  Newspaper,
  Megaphone,
  Speaker,
  Volume2,
  PlayCircle,
  Clock,
  Calendar,
  CalendarDays,
  MapPinned,
  Navigation,
  Link2,
  Lightbulb,
  Shield,
  Lock,
  Unlock,
  KeyRound,
  Rows3,
  LayoutGrid,
  Wallet2,
  PiggyBank,
  Coins,
  Banknote,
  Landmark,
  Scale,
  FileText,
  ClipboardList,
  CheckCircle2,
  ThumbsDown,
  QrCode,
  Paintbrush,
  Baby,
  Dog,
  Cat,
} from "lucide-react";

export interface LibraryIcon {
  key: string;
  label: string;
  category: string;
  // ComponentType<{className?:string}> (bukan LucideIcon murni) -- lihat
  // catatan lengkap kenapa di komentar header file ini (kategori "Media
  // Sosial" butuh ikon brand dari icons.tsx, bukan lucide-react).
  Icon: LucideIcon | ComponentType<{ className?: string }>;
}

// Kategori disusun sesuai jenis konten yang biasa dipakai kreator link-in-
// bio Indonesia (media sosial, toko, kuliner, kelas/edukasi, dst) --
// urutan array = urutan tampil di IconPickerModal, "Semua" (pencarian
// tanpa kategori) tetap menampilkan seluruhnya.
export const ICON_LIBRARY: LibraryIcon[] = [
  // Media Sosial -- permintaan langsung pengguna, 20 Agustus 2026:
  // "tambahkan juga di bagian icon supaya bisa dipilih" (susulan
  // penggantian ikon sosmed hand-drawn di icons.tsx jadi Simple Icons
  // asli). Ditaruh PALING ATAS (bukan digabung ke "Komunikasi & Sosial"
  // generik di bawah) supaya jadi kategori pertama yang terlihat -- sesuai
  // penekanan pengguna "terutama sosmed icon". Key prefix "brand-" (bukan
  // nama platform polos) supaya tidak bentrok kalau suatu saat lucide-react
  // punya key dengan nama sama.
  { key: "brand-instagram", label: "Instagram", category: "Media Sosial", Icon: IconInstagram },
  { key: "brand-tiktok", label: "TikTok", category: "Media Sosial", Icon: IconTiktok },
  { key: "brand-youtube", label: "YouTube", category: "Media Sosial", Icon: IconYoutube },
  { key: "brand-whatsapp", label: "WhatsApp", category: "Media Sosial", Icon: IconWhatsapp },
  { key: "brand-facebook", label: "Facebook", category: "Media Sosial", Icon: IconFacebook },
  { key: "brand-x", label: "X (Twitter)", category: "Media Sosial", Icon: IconX },
  { key: "brand-linkedin", label: "LinkedIn", category: "Media Sosial", Icon: IconLinkedin },
  { key: "brand-telegram", label: "Telegram", category: "Media Sosial", Icon: IconTelegram },
  { key: "brand-spotify", label: "Spotify", category: "Media Sosial", Icon: IconSpotify },
  { key: "brand-discord", label: "Discord", category: "Media Sosial", Icon: IconDiscord },
  { key: "brand-twitch", label: "Twitch", category: "Media Sosial", Icon: IconTwitch },
  { key: "brand-shopee", label: "Shopee", category: "Media Sosial", Icon: IconShopee },
  { key: "brand-apple-music", label: "Apple Music", category: "Media Sosial", Icon: IconAppleMusic },
  { key: "brand-apple-podcasts", label: "Apple Podcasts", category: "Media Sosial", Icon: IconApplePodcasts },
  { key: "brand-google-maps", label: "Google Maps", category: "Media Sosial", Icon: IconGoogleMaps },

  // Komunikasi & Sosial
  { key: "message-circle", label: "Pesan", category: "Komunikasi & Sosial", Icon: MessageCircle },
  { key: "message-square", label: "Chat", category: "Komunikasi & Sosial", Icon: MessageSquare },
  { key: "send", label: "Kirim", category: "Komunikasi & Sosial", Icon: Send },
  { key: "mail", label: "Email", category: "Komunikasi & Sosial", Icon: Mail },
  { key: "phone", label: "Telepon", category: "Komunikasi & Sosial", Icon: Phone },
  { key: "phone-call", label: "Hubungi", category: "Komunikasi & Sosial", Icon: PhoneCall },
  { key: "video", label: "Video Call", category: "Komunikasi & Sosial", Icon: Video },
  { key: "mic", label: "Mikrofon", category: "Komunikasi & Sosial", Icon: Mic },
  { key: "mic-2", label: "Podcast", category: "Komunikasi & Sosial", Icon: Mic2 },
  { key: "users", label: "Komunitas", category: "Komunikasi & Sosial", Icon: Users },
  { key: "user", label: "Profil", category: "Komunikasi & Sosial", Icon: User },
  { key: "user-plus", label: "Follow", category: "Komunikasi & Sosial", Icon: UserPlus },
  { key: "heart", label: "Suka", category: "Komunikasi & Sosial", Icon: Heart },
  { key: "heart-handshake", label: "Dukungan", category: "Komunikasi & Sosial", Icon: HeartHandshake },
  { key: "thumbs-up", label: "Jempol", category: "Komunikasi & Sosial", Icon: ThumbsUp },
  { key: "thumbs-down", label: "Tidak Suka", category: "Komunikasi & Sosial", Icon: ThumbsDown },
  { key: "share-2", label: "Bagikan", category: "Komunikasi & Sosial", Icon: Share2 },
  { key: "at-sign", label: "Username", category: "Komunikasi & Sosial", Icon: AtSign },
  { key: "hash", label: "Hashtag", category: "Komunikasi & Sosial", Icon: Hash },
  { key: "rss", label: "Feed", category: "Komunikasi & Sosial", Icon: Rss },
  { key: "bell", label: "Notifikasi", category: "Komunikasi & Sosial", Icon: Bell },
  { key: "megaphone", label: "Pengumuman", category: "Komunikasi & Sosial", Icon: Megaphone },
  { key: "newspaper", label: "Berita", category: "Komunikasi & Sosial", Icon: Newspaper },

  // Toko & Bisnis
  { key: "shopping-bag", label: "Belanja", category: "Toko & Bisnis", Icon: ShoppingBag },
  { key: "shopping-cart", label: "Keranjang", category: "Toko & Bisnis", Icon: ShoppingCart },
  { key: "store", label: "Toko", category: "Toko & Bisnis", Icon: Store },
  { key: "tag", label: "Label Harga", category: "Toko & Bisnis", Icon: Tag },
  { key: "tags", label: "Kategori", category: "Toko & Bisnis", Icon: Tags },
  { key: "credit-card", label: "Kartu", category: "Toko & Bisnis", Icon: CreditCard },
  { key: "wallet", label: "Dompet", category: "Toko & Bisnis", Icon: Wallet },
  { key: "wallet-2", label: "Dompet Digital", category: "Toko & Bisnis", Icon: Wallet2 },
  { key: "dollar-sign", label: "Harga", category: "Toko & Bisnis", Icon: DollarSign },
  { key: "receipt", label: "Struk", category: "Toko & Bisnis", Icon: Receipt },
  { key: "package", label: "Paket", category: "Toko & Bisnis", Icon: Package },
  { key: "gift", label: "Hadiah", category: "Toko & Bisnis", Icon: Gift },
  { key: "percent", label: "Diskon", category: "Toko & Bisnis", Icon: Percent },
  { key: "briefcase", label: "Kerja", category: "Toko & Bisnis", Icon: Briefcase },
  { key: "building", label: "Kantor", category: "Toko & Bisnis", Icon: Building },
  { key: "building-2", label: "Gedung", category: "Toko & Bisnis", Icon: Building2 },
  { key: "trending-up", label: "Pertumbuhan", category: "Toko & Bisnis", Icon: TrendingUp },
  { key: "bar-chart", label: "Grafik Batang", category: "Toko & Bisnis", Icon: BarChart },
  { key: "pie-chart", label: "Grafik Lingkaran", category: "Toko & Bisnis", Icon: PieChart },
  { key: "target", label: "Target", category: "Toko & Bisnis", Icon: Target },
  { key: "award", label: "Penghargaan", category: "Toko & Bisnis", Icon: Award },
  { key: "handshake", label: "Kerja Sama", category: "Toko & Bisnis", Icon: Handshake },
  { key: "piggy-bank", label: "Tabungan", category: "Toko & Bisnis", Icon: PiggyBank },
  { key: "coins", label: "Koin", category: "Toko & Bisnis", Icon: Coins },
  { key: "banknote", label: "Uang", category: "Toko & Bisnis", Icon: Banknote },
  { key: "landmark", label: "Bank", category: "Toko & Bisnis", Icon: Landmark },
  { key: "scale", label: "Timbangan", category: "Toko & Bisnis", Icon: Scale },
  { key: "file-text", label: "Dokumen", category: "Toko & Bisnis", Icon: FileText },
  { key: "clipboard-list", label: "Daftar", category: "Toko & Bisnis", Icon: ClipboardList },
  { key: "qr-code", label: "Kode QR", category: "Toko & Bisnis", Icon: QrCode },

  // Makanan & Minuman
  { key: "coffee", label: "Kopi", category: "Makanan & Minuman", Icon: Coffee },
  { key: "pizza", label: "Pizza", category: "Makanan & Minuman", Icon: Pizza },
  { key: "ice-cream", label: "Es Krim", category: "Makanan & Minuman", Icon: IceCream },
  { key: "cake", label: "Kue", category: "Makanan & Minuman", Icon: Cake },
  { key: "utensils", label: "Makan", category: "Makanan & Minuman", Icon: Utensils },
  { key: "utensils-crossed", label: "Restoran", category: "Makanan & Minuman", Icon: UtensilsCrossed },
  { key: "wine", label: "Anggur", category: "Makanan & Minuman", Icon: Wine },
  { key: "beer", label: "Bir", category: "Makanan & Minuman", Icon: Beer },
  { key: "martini", label: "Koktail", category: "Makanan & Minuman", Icon: Martini },
  { key: "cup-soda", label: "Minuman", category: "Makanan & Minuman", Icon: CupSoda },
  { key: "soup", label: "Sup", category: "Makanan & Minuman", Icon: Soup },
  { key: "salad", label: "Salad", category: "Makanan & Minuman", Icon: Salad },
  { key: "apple", label: "Buah", category: "Makanan & Minuman", Icon: Apple },
  { key: "cherry", label: "Ceri", category: "Makanan & Minuman", Icon: Cherry },
  { key: "croissant", label: "Roti", category: "Makanan & Minuman", Icon: Croissant },
  { key: "popcorn", label: "Popcorn", category: "Makanan & Minuman", Icon: Popcorn },

  // Perjalanan & Lokasi
  { key: "plane", label: "Pesawat", category: "Perjalanan & Lokasi", Icon: Plane },
  { key: "car", label: "Mobil", category: "Perjalanan & Lokasi", Icon: Car },
  { key: "bike", label: "Sepeda", category: "Perjalanan & Lokasi", Icon: Bike },
  { key: "train", label: "Kereta", category: "Perjalanan & Lokasi", Icon: Train },
  { key: "ship", label: "Kapal", category: "Perjalanan & Lokasi", Icon: Ship },
  { key: "map-pin", label: "Lokasi", category: "Perjalanan & Lokasi", Icon: MapPin },
  { key: "map-pinned", label: "Peta Lokasi", category: "Perjalanan & Lokasi", Icon: MapPinned },
  { key: "map", label: "Peta", category: "Perjalanan & Lokasi", Icon: Map },
  { key: "navigation", label: "Navigasi", category: "Perjalanan & Lokasi", Icon: Navigation },
  { key: "compass", label: "Kompas", category: "Perjalanan & Lokasi", Icon: Compass },
  { key: "globe", label: "Dunia", category: "Perjalanan & Lokasi", Icon: Globe },
  { key: "luggage", label: "Koper", category: "Perjalanan & Lokasi", Icon: Luggage },
  { key: "backpack", label: "Ransel", category: "Perjalanan & Lokasi", Icon: Backpack },
  { key: "palmtree", label: "Pantai", category: "Perjalanan & Lokasi", Icon: Palmtree },
  { key: "mountain", label: "Gunung", category: "Perjalanan & Lokasi", Icon: Mountain },
  { key: "tent", label: "Camping", category: "Perjalanan & Lokasi", Icon: Tent },

  // Musik & Hiburan
  { key: "music", label: "Musik", category: "Musik & Hiburan", Icon: Music },
  { key: "music-2", label: "Nada", category: "Musik & Hiburan", Icon: Music2 },
  { key: "music-3", label: "Not Musik", category: "Musik & Hiburan", Icon: Music3 },
  { key: "music-4", label: "Lagu", category: "Musik & Hiburan", Icon: Music4 },
  { key: "headphones", label: "Headphone", category: "Musik & Hiburan", Icon: Headphones },
  { key: "radio", label: "Radio", category: "Musik & Hiburan", Icon: Radio },
  { key: "disc", label: "Album", category: "Musik & Hiburan", Icon: Disc },
  { key: "disc-3", label: "Vinyl", category: "Musik & Hiburan", Icon: Disc3 },
  { key: "film", label: "Film", category: "Musik & Hiburan", Icon: Film },
  { key: "clapperboard", label: "Produksi", category: "Musik & Hiburan", Icon: Clapperboard },
  { key: "tv", label: "TV", category: "Musik & Hiburan", Icon: Tv },
  { key: "gamepad", label: "Game", category: "Musik & Hiburan", Icon: Gamepad },
  { key: "gamepad-2", label: "Kontroler", category: "Musik & Hiburan", Icon: Gamepad2 },
  { key: "party-popper", label: "Perayaan", category: "Musik & Hiburan", Icon: PartyPopper },
  { key: "ticket", label: "Tiket", category: "Musik & Hiburan", Icon: Ticket },
  { key: "speaker", label: "Speaker", category: "Musik & Hiburan", Icon: Speaker },
  { key: "volume-2", label: "Suara", category: "Musik & Hiburan", Icon: Volume2 },
  { key: "play-circle", label: "Putar", category: "Musik & Hiburan", Icon: PlayCircle },

  // Olahraga & Kebugaran
  { key: "dumbbell", label: "Gym", category: "Olahraga & Kebugaran", Icon: Dumbbell },
  { key: "trophy", label: "Piala", category: "Olahraga & Kebugaran", Icon: Trophy },
  { key: "medal", label: "Medali", category: "Olahraga & Kebugaran", Icon: Medal },
  { key: "volleyball", label: "Bola Voli", category: "Olahraga & Kebugaran", Icon: Volleyball },
  { key: "activity", label: "Aktivitas", category: "Olahraga & Kebugaran", Icon: Activity },
  { key: "flame", label: "Kalori", category: "Olahraga & Kebugaran", Icon: Flame },
  { key: "zap", label: "Energi", category: "Olahraga & Kebugaran", Icon: Zap },
  { key: "timer", label: "Timer", category: "Olahraga & Kebugaran", Icon: Timer },

  // Teknologi
  { key: "laptop", label: "Laptop", category: "Teknologi", Icon: Laptop },
  { key: "smartphone", label: "HP", category: "Teknologi", Icon: Smartphone },
  { key: "monitor", label: "Monitor", category: "Teknologi", Icon: Monitor },
  { key: "camera", label: "Kamera", category: "Teknologi", Icon: Camera },
  { key: "cpu", label: "Prosesor", category: "Teknologi", Icon: Cpu },
  { key: "wifi", label: "WiFi", category: "Teknologi", Icon: Wifi },
  { key: "bluetooth", label: "Bluetooth", category: "Teknologi", Icon: Bluetooth },
  { key: "code", label: "Kode", category: "Teknologi", Icon: Code },
  { key: "terminal", label: "Terminal", category: "Teknologi", Icon: Terminal },
  { key: "database", label: "Database", category: "Teknologi", Icon: Database },
  { key: "cloud", label: "Cloud", category: "Teknologi", Icon: Cloud },
  { key: "rocket", label: "Roket", category: "Teknologi", Icon: Rocket },
  { key: "battery", label: "Baterai", category: "Teknologi", Icon: Battery },
  { key: "printer", label: "Printer", category: "Teknologi", Icon: Printer },
  { key: "keyboard", label: "Keyboard", category: "Teknologi", Icon: Keyboard },
  { key: "mouse", label: "Mouse", category: "Teknologi", Icon: Mouse },
  { key: "hard-drive", label: "Penyimpanan", category: "Teknologi", Icon: HardDrive },
  { key: "link-2", label: "Tautan", category: "Teknologi", Icon: Link2 },
  { key: "lightbulb", label: "Ide", category: "Teknologi", Icon: Lightbulb },
  { key: "layout-grid", label: "Grid", category: "Teknologi", Icon: LayoutGrid },
  { key: "rows-3", label: "Daftar Baris", category: "Teknologi", Icon: Rows3 },

  // Alam & Cuaca
  { key: "sun", label: "Matahari", category: "Alam & Cuaca", Icon: Sun },
  { key: "moon", label: "Bulan", category: "Alam & Cuaca", Icon: Moon },
  { key: "star", label: "Bintang", category: "Alam & Cuaca", Icon: Star },
  { key: "cloud-rain", label: "Hujan", category: "Alam & Cuaca", Icon: CloudRain },
  { key: "snowflake", label: "Salju", category: "Alam & Cuaca", Icon: Snowflake },
  { key: "wind", label: "Angin", category: "Alam & Cuaca", Icon: Wind },
  { key: "umbrella", label: "Payung", category: "Alam & Cuaca", Icon: Umbrella },
  { key: "leaf", label: "Daun", category: "Alam & Cuaca", Icon: Leaf },
  { key: "flower", label: "Bunga", category: "Alam & Cuaca", Icon: Flower },
  { key: "flower-2", label: "Bunga Mekar", category: "Alam & Cuaca", Icon: Flower2 },
  { key: "trees", label: "Pepohonan", category: "Alam & Cuaca", Icon: Trees },
  { key: "tree-pine", label: "Pinus", category: "Alam & Cuaca", Icon: TreePine },
  { key: "droplet", label: "Tetesan Air", category: "Alam & Cuaca", Icon: Droplet },
  { key: "waves", label: "Ombak", category: "Alam & Cuaca", Icon: Waves },
  { key: "sunrise", label: "Fajar", category: "Alam & Cuaca", Icon: Sunrise },
  { key: "sunset", label: "Senja", category: "Alam & Cuaca", Icon: Sunset },
  { key: "sprout", label: "Tunas", category: "Alam & Cuaca", Icon: Sprout },
  { key: "paw-print", label: "Hewan", category: "Alam & Cuaca", Icon: PawPrint },
  { key: "fish", label: "Ikan", category: "Alam & Cuaca", Icon: Fish },
  { key: "bird", label: "Burung", category: "Alam & Cuaca", Icon: Bird },
  { key: "bug", label: "Serangga", category: "Alam & Cuaca", Icon: Bug },
  { key: "rabbit", label: "Kelinci", category: "Alam & Cuaca", Icon: Rabbit },
  { key: "turtle", label: "Kura-kura", category: "Alam & Cuaca", Icon: Turtle },
  { key: "dog", label: "Anjing", category: "Alam & Cuaca", Icon: Dog },
  { key: "cat", label: "Kucing", category: "Alam & Cuaca", Icon: Cat },

  // Seni & Kreativitas
  { key: "palette", label: "Palet Warna", category: "Seni & Kreativitas", Icon: Palette },
  { key: "brush", label: "Kuas", category: "Seni & Kreativitas", Icon: Brush },
  { key: "paintbrush", label: "Cat", category: "Seni & Kreativitas", Icon: Paintbrush },
  { key: "pen-tool", label: "Desain", category: "Seni & Kreativitas", Icon: PenTool },
  { key: "pencil", label: "Pensil", category: "Seni & Kreativitas", Icon: Pencil },
  { key: "scissors", label: "Gunting", category: "Seni & Kreativitas", Icon: Scissors },
  { key: "image", label: "Gambar", category: "Seni & Kreativitas", Icon: Image },
  { key: "images", label: "Galeri", category: "Seni & Kreativitas", Icon: Images },
  { key: "sparkles", label: "Kilau", category: "Seni & Kreativitas", Icon: Sparkles },
  { key: "sparkle", label: "Bintang Kilau", category: "Seni & Kreativitas", Icon: Sparkle },
  { key: "wand-2", label: "Sulap", category: "Seni & Kreativitas", Icon: Wand2 },
  { key: "book", label: "Buku", category: "Seni & Kreativitas", Icon: Book },
  { key: "book-open", label: "Buku Terbuka", category: "Seni & Kreativitas", Icon: BookOpen },
  { key: "bookmark", label: "Bookmark", category: "Seni & Kreativitas", Icon: Bookmark },
  { key: "feather", label: "Bulu", category: "Seni & Kreativitas", Icon: Feather },

  // Rumah & Gaya Hidup
  { key: "home", label: "Rumah", category: "Rumah & Gaya Hidup", Icon: Home },
  { key: "sofa", label: "Sofa", category: "Rumah & Gaya Hidup", Icon: Sofa },
  { key: "bed", label: "Kasur", category: "Rumah & Gaya Hidup", Icon: Bed },
  { key: "lamp", label: "Lampu", category: "Rumah & Gaya Hidup", Icon: Lamp },
  { key: "key", label: "Kunci", category: "Rumah & Gaya Hidup", Icon: Key },
  { key: "shower-head", label: "Shower", category: "Rumah & Gaya Hidup", Icon: ShowerHead },
  { key: "bath", label: "Kamar Mandi", category: "Rumah & Gaya Hidup", Icon: Bath },
  { key: "shirt", label: "Baju", category: "Rumah & Gaya Hidup", Icon: Shirt },
  { key: "watch", label: "Jam Tangan", category: "Rumah & Gaya Hidup", Icon: Watch },
  { key: "glasses", label: "Kacamata", category: "Rumah & Gaya Hidup", Icon: Glasses },
  { key: "crown", label: "Mahkota", category: "Rumah & Gaya Hidup", Icon: Crown },
  { key: "gem", label: "Perhiasan", category: "Rumah & Gaya Hidup", Icon: Gem },
  { key: "baby", label: "Bayi", category: "Rumah & Gaya Hidup", Icon: Baby },

  // Edukasi
  { key: "graduation-cap", label: "Wisuda", category: "Edukasi", Icon: GraduationCap },
  { key: "school", label: "Sekolah", category: "Edukasi", Icon: School },
  { key: "calculator", label: "Kalkulator", category: "Edukasi", Icon: Calculator },
  { key: "ruler", label: "Penggaris", category: "Edukasi", Icon: Ruler },
  { key: "library", label: "Perpustakaan", category: "Edukasi", Icon: Library },
  { key: "calendar", label: "Kalender", category: "Edukasi", Icon: Calendar },
  { key: "calendar-days", label: "Jadwal", category: "Edukasi", Icon: CalendarDays },
  { key: "clock", label: "Waktu", category: "Edukasi", Icon: Clock },

  // Kesehatan
  { key: "heart-pulse", label: "Detak Jantung", category: "Kesehatan", Icon: HeartPulse },
  { key: "stethoscope", label: "Dokter", category: "Kesehatan", Icon: Stethoscope },
  { key: "pill", label: "Obat", category: "Kesehatan", Icon: Pill },
  { key: "syringe", label: "Suntik", category: "Kesehatan", Icon: Syringe },
  { key: "brain", label: "Pikiran", category: "Kesehatan", Icon: Brain },
  { key: "eye", label: "Mata", category: "Kesehatan", Icon: Eye },
  { key: "smile", label: "Senyum", category: "Kesehatan", Icon: Smile },

  // Lainnya
  { key: "diamond", label: "Berlian", category: "Lainnya", Icon: Diamond },
  { key: "flag", label: "Bendera", category: "Lainnya", Icon: Flag },
  { key: "anchor", label: "Jangkar", category: "Lainnya", Icon: Anchor },
  { key: "puzzle", label: "Puzzle", category: "Lainnya", Icon: Puzzle },
  { key: "infinity", label: "Tak Terbatas", category: "Lainnya", Icon: Infinity },
  { key: "shield", label: "Perlindungan", category: "Lainnya", Icon: Shield },
  { key: "lock", label: "Terkunci", category: "Lainnya", Icon: Lock },
  { key: "unlock", label: "Terbuka", category: "Lainnya", Icon: Unlock },
  { key: "key-round", label: "Kunci Akses", category: "Lainnya", Icon: KeyRound },
  { key: "check-circle-2", label: "Terverifikasi", category: "Lainnya", Icon: CheckCircle2 },
];

// getLibraryIcon -- lookup cepat berdasarkan icon_key (links.icon_key,
// migrasi 000066). Dipakai baik oleh dashboard (IconPickerModal, badge
// preview) MAUPUN PagePreview.tsx (halaman publik/pratinjau) -- SATU
// sumber kebenaran render supaya keduanya selalu tampil identik.
const ICON_LIBRARY_MAP: Record<string, LibraryIcon> = Object.fromEntries(ICON_LIBRARY.map((i) => [i.key, i]));

export function getLibraryIcon(key: string | undefined | null): LibraryIcon | undefined {
  if (!key) return undefined;
  return ICON_LIBRARY_MAP[key];
}

export const ICON_LIBRARY_CATEGORIES: string[] = Array.from(new Set(ICON_LIBRARY.map((i) => i.category)));
