// TECH_BRAND_PATHS -- path SVG logo teknologi & platform (simple-icons,
// lisensi CC0) utk kategori galeri ikon "Teknologi & Platform" (24
// September 2026, chip keahlian layout "Profil Kreator": React/Laravel/Go
// dst). Modul TERPISAH yang HANYA dimuat lazy lewat techBrandIcon()
// (lib/icon-library.ts) -- diukur: 33 path ini ~14 KB gzip, terlalu mahal
// kalau ikut bundle galeri yang dimuat SETIAP halaman publik. Named import
// supaya bundler hanya membawa 33 ikon ini, bukan seluruh simple-icons.
import {
  siReact,
  siLaravel,
  siGo,
  siJavascript,
  siTypescript,
  siPython,
  siPhp,
  siKotlin,
  siSwift,
  siFlutter,
  siNodedotjs,
  siNextdotjs,
  siVuedotjs,
  siTailwindcss,
  siDocker,
  siFigma,
  siWordpress,
  siNotion,
  siGithub,
  siBlender,
  siBehance,
  siDribbble,
  siMedium,
  siSubstack,
  siGoodreads,
  siWattpad,
  siSoundcloud,
  siZoom,
  siGooglemeet,
  siGoogleclassroom,
  siGrab,
  siGojek,
  siThreads,
} from "simple-icons";

export const TECH_BRAND_PATHS: Record<string, string> = {
  react: siReact.path,
  laravel: siLaravel.path,
  go: siGo.path,
  javascript: siJavascript.path,
  typescript: siTypescript.path,
  python: siPython.path,
  php: siPhp.path,
  kotlin: siKotlin.path,
  swift: siSwift.path,
  flutter: siFlutter.path,
  nodedotjs: siNodedotjs.path,
  nextdotjs: siNextdotjs.path,
  vuedotjs: siVuedotjs.path,
  tailwindcss: siTailwindcss.path,
  docker: siDocker.path,
  figma: siFigma.path,
  wordpress: siWordpress.path,
  notion: siNotion.path,
  github: siGithub.path,
  blender: siBlender.path,
  behance: siBehance.path,
  dribbble: siDribbble.path,
  medium: siMedium.path,
  substack: siSubstack.path,
  goodreads: siGoodreads.path,
  wattpad: siWattpad.path,
  soundcloud: siSoundcloud.path,
  zoom: siZoom.path,
  googlemeet: siGooglemeet.path,
  googleclassroom: siGoogleclassroom.path,
  grab: siGrab.path,
  gojek: siGojek.path,
  threads: siThreads.path,
};
