run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - bodyclose

issues:
  exclude-dirs:
    - bin
